
services:
  # PostgreSQL database for source data
  postgres:
    image: debezium/postgres:14
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=codeshard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c wal_level=logical -c max_wal_senders=4 -c max_replication_slots=4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  # Initialize PostgreSQL database
  postgres-init:
    image: debezium/postgres:14
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./postgres-init.sql:/postgres-init.sql
    command: >
      bash -c '
        echo "Initializing PostgreSQL database..."
        PGPASSWORD=postgres psql -h postgres -U postgres -d codeshard -f /postgres-init.sql
        echo "PostgreSQL initialization completed successfully."
      '
    restart: on-failure

  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    platform: linux/amd64
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka-init:
    image: confluentinc/cp-kafka:7.3.0
    platform: linux/amd64
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c '
        echo "Waiting for Kafka to be ready..."
        sleep 10
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic postgres.codeshard.likes --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic postgres.codeshard.shards --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic postgres.codeshard.followers --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic postgres.codeshard.comments --partitions 3 --replication-factor 1
        echo "Kafka topics created"
      '
    restart: on-failure

  cassandra:
    image: cassandra:4.1
    platform: linux/amd64
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=flink_cluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cassandra-init:
    image: cassandra:4.1
    platform: linux/amd64
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra-init.cql:/cassandra-init.cql
    command: >
      bash -c '
        echo "Waiting for Cassandra to be ready..."
        sleep 30
        echo "Creating keyspace and tables..."
        cqlsh cassandra -f /cassandra-init.cql
        echo "Keyspace and tables created."
      '
    restart: on-failure

  jobmanager:
    image: flink:1.17
    platform: linux/amd64
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink-connectors:/flink-connectors
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  taskmanager:
    image: flink:1.17
    platform: linux/amd64
    depends_on:
      jobmanager:
        condition: service_healthy
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./flink-connectors:/flink-connectors
    restart: unless-stopped

  # Debezium Connect for PostgreSQL CDC
  debezium-connect:
    image: debezium/connect:2.5
    platform: linux/amd64
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  debezium-config:
    image: curlimages/curl:7.83.1
    platform: linux/amd64
    depends_on:
      debezium-connect:
        condition: service_healthy
    volumes:
      - ./debezium-connectors:/connectors
    command: >
      sh -c '
        echo "Waiting for Debezium Connect to be ready..."
        until curl -s debezium-connect:8083/connectors >/dev/null; do
          echo "Debezium Connect not ready yet, waiting..."
          sleep 5
        done
        echo "Creating Debezium connectors..."
        for connector in /connectors/*.json; do
          if [ -f "$connector" ]; then
            connector_name=$(basename "$connector" .json)
            echo "Creating connector: $connector_name"
            curl -X POST -H "Content-Type: application/json" --data @"$connector" http://debezium-connect:8083/connectors
          fi
        done
        echo "Connectors created successfully."
      '
    restart: on-failure
  

  ## Redis 
  redis:
    image: redis:7
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FastAPI application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      jobmanager:
        condition: service_healthy
      debezium-connect:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=codeshard
      - CASSANDRA_TABLE=user_activity
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeshard
      - DEBEZIUM_CONNECT_URL=http://debezium-connect:8083
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped

volumes:
  cassandra_data:
  postgres_data:
  redis_data: